Edit UG to include findMember and findEvent commands
AY2324S1-CS2103T-F11-1/tp pull request #166
Opened 2023-10-26 15:48 UTC by SelwynAng

Edited User Guide to include `findMember` and `findEvent` command descriptions and summaries.

2023-10-26 17:27 UTC, wr1159 requested changes
I believe this is confused with viewMember and viewEvent

2023-10-26 19:10 UTC, andrechuakj requested changes
Just a small correction

2023-10-26 19:10 UTC, andrechuakj commented on docs/UserGuide.md
> +* `findMember party marathon gaming` displays the event(s) which name(s) contain 'party', 'marathon' and/or 'gaming'.
```suggestion
* `findEvent party marathon gaming` displays the event(s) which name(s) contain 'party', 'marathon' and/or 'gaming'.
```

2023-10-27 00:02 UTC, SelwynAng commented on docs/UserGuide.md
> +* `findMember party marathon gaming` displays the event(s) which name(s) contain 'party', 'marathon' and/or 'gaming'.
Ok will correct this!

2023-10-27 00:03 UTC, wr1159 approved these changes
LGTM

2023-10-27 00:05 UTC, andrechuakj approved these changes
LGTM

2023-10-27 00:05 UTC, merged